### ISSUE TITLE
StatefulTechnicalAnalysers.py

### ISSUE THREAD

**Issue by iLampard** [wegamekinglc/Finance-Python#3]
PyFin/Analysis/TechnicalAnalysis/StatefulTechnicalAnalysers.py
line 140 

for k, v in t.value.items():
        print(k, v)

运行该py会在140行报错: t.value是pd.Series type，没有.items方法。如下修改便可以通过

for k, v in t.value.to_dict().items()   #以前的版本value是dict type?

**Comment by wegamekinglc** [comment]
没有，一直是Series类型。我估计是python2和python3的区别，我在python3下，Series是有items方法的
