### ISSUE TITLE
 No module named 'PyFin.DateUtilities.Calendar'

### ISSUE THREAD

**Issue by fswzb** [wegamekinglc/Finance-Python#6]
No module named 'PyFin.DateUtilities.Calendar',运行出错，不知是否与下面错误有关：
(c) 2012 Microsoft Corporation。保留所有权利。

C:\www\Finance-Python>py -3.5 setup.py build_ext --inplace --compiler=msvc
running build_ext
building 'PyFin.Analysis.SecurityValues' extension
error: Unable to find vcvarsall.bat

**Comment by wegamekinglc** [comment]
@fswzb 下面有报错信息，是说``error: Unable to find vcvarsall.bat``。也就是在你的机器上无法找到c/c++编译器。建议安装好Visual Studio 2015以后再试。

**Comment by fswzb** [comment]
装vs后py -3.5 setup.py build_ext --inplace --compiler=msvc，能够运行了，谢谢！
